### ISSUE TITLE
CanJS TodoMVC tests are failing

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3462]
The TodoMVC tests here are failing right now: https://github.com/canjs/canjs/blob/master/docs/can-guides/experiment/todomvc/test.js

I noticed this because the build for a different PR failed: https://travis-ci.org/canjs/canjs/builds/258734621

I can reproduce this by loading the TodoMVC app file locally: https://github.com/canjs/canjs/blob/3833e8b7e512ae9f545eba4d1b000a363423ccc2/docs/can-guides/experiment/todomvc/todomvc.html

It throws on this line: https://github.com/canjs/can-view-scope/blob/db3565d447f5437f266313b6b6fb8e1cb442cb60/can-view-scope.js#L378

**Comment by Sinjhin** [comment]
This is actually fixed with `can-view-scope` version `3.3.1`.

Referenced PR is going away.

**Comment by phillipskevin** [comment]
So we'll need to get https://github.com/canjs/canjs/pull/3423 in before we close this issue out. It looks like that PR doesn't have the same failures as the rest of these, but some tests are still failing. @Sinjhin do you want to look into that?

You may just also need https://github.com/canjs/canjs/pull/3422. The fix in can-view-scope went along with https://github.com/canjs/can-observation/releases/tag/v3.3.2.

**Comment by Sinjhin** [comment]
Tests are passing in master now.
